export { Parser } from './parser.ts'
export type { Options } from './parser.ts'
export { unescapeEntity } from './unescape.ts'
export type { UnescapeOptions } from './unescape.ts'
export { Node } from './xml.ts'
